### ISSUE TITLE
"There is no entry for OVERCAST for dynamic switches..."

### ISSUE THREAD

**Issue by xProlithium** [justalemon/SimpleSync#38]
Grabbed this because having desync between players in regards to time/weather is the easiest way to break somebody's immersion and gameplay.

However, this message keeps showing up in the log.

Any information or assistance would be appreciated.

![mstsc_LxC4UvKfQE](https://user-images.githubusercontent.com/7946481/79453052-1f5aab80-7fb7-11ea-81aa-c094553318cc.png)

**Comment by justalemon** [comment]
The message is trying to say that [Switch.json](https://github.com/justalemon/SimpleSync/blob/master/SimpleSync.Server/Switch.json) does not contain possible switches for the OVERCAST weather.

See the following section as an example:

```
    "CLEAR": [
        "CLEARING",
        "OVERCAST"
    ],
```

When the weather is CLEAR, it is going to change to either CLEARING or OVERCAST. If you check the file, there is no entry for OVERCAST so that is going to end up with a default value to prevent crashes (CLEAR).

I just need to add an entry for OVERCAST and this will be fixed.

If you don't want to wait, you can just add your own entries and restart the resource.

**Comment by xProlithium** [comment]
It's not server breaking, and I'm prone to break things by poking them. I'm fine with waiting. Thanks for answering, and an excellent script! :)
